### ISSUE TITLE
Hat visibility glitch

### ISSUE THREAD

**Issue by ParticIe** [matthewdean/roblox-asset-bug-tracker#16]
As shown in the picture, there is a hat listed as "Gnome" which isn't visible on the character's head while worn in-game. It does not appear on the site, either. It seems to have been an issue for a while now, because I've owned the hat since 2012, and the glitch has still been occurring. Many people have also been requesting that someone fixes this in the comments of the hat.

HatId: http://www.roblox.com/Gnome-item?id=45941295

![glitch](https://cloud.githubusercontent.com/assets/9423236/4799950/2be141b0-5e21-11e4-941b-9138fabee20d.png)

**Comment by magiccube3** [comment]
Can't replicate: http://i.imgur.com/h9QCRug.png

**Comment by matthewdean** [comment]
Fixed.
